config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :superheros
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/superhero.rb
class Superhero < ApplicationRecord
  belongs_to :team
  validates :name, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :superheros
  accepts_nested_attributes_for :superheros
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :set_superhero, only: [:edit, :update, :show, :destroy]

  def show
  end

  def index
    @superheros = Superhero.all
  end

  def new
    @superhero = Superhero.new

  end

  def create
    @superhero = Superhero.new(superhero_params)
    if @superhero.save
      redirect_to @superhero
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @superhero.update(superhero_params)
      redirect_to @superhero
    else
      render :edit
    end
  end

  def destroy
    @superhero.destroy
    redirect_to :superheros_path
  end

  private

  def superhero_params
    params.require(:superhero).permit(:name, :alias, :power, :power_level, :team_id)
  end

  def set_superhero
    @superhero = Superhero.find(params[:id])
  end


end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_action :set_team, only: [:show]
  layout "team"

  def index
    @teams = Team.all

    # render layout: false
  end

  def show
  end

  def new
    @team = Team.new
    3.times do
      @team.superheros.build
    end
  end

  def create
    @team = Team.create(team_params)
    if @team.valid?
      redirect_to @team
    else
      render :new
    end
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name, :locality, :established, superheros_attributes: [:name, :alias, :power, :power_level])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KAMALA'S SUPERHERO FANPAGE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Welcome to KAMALA KHAN'S SUPERHERO FANPAGE</h1>
    <h2>The BEST fanpage for individual superheroes to ever come out of Jersey City!</h2>
    <%= yield %>
    <%= link_to "View All Superheros", superheros_path %> | <%= link_to "Add A Superhero", new_superhero_path %> | <%= link_to "Go To My Teams Tracker!", teams_path %>
  </body>
</html>

app/views/layouts/team.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KAMALA'S TEAM TRACKER</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>FOR THE JOB SEARCH: POTENTIAL TEAMS</h1>
    <%= yield %>
    <%= link_to "Go To My Superheroes Website", superheros_path %> | <%= link_to "See All Teams", teams_path %> | <%= link_to "Add A Team", new_team_path %>
  </body>
</html>

app/views/superheros/_form.html.erb
<%= form_for @superhero do |f| %>
  <%= render partial:"formpart", locals:{f: f} %>
  <%= f.label :team_id %>
  <%= f.collection_select :team_id, Team.all, :id, :name %><br><br>
  <%= f.submit %>
<% end %>

app/views/superheros/_formpart.html.erb
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :alias %>
  <%= f.text_field :alias %><br>
  <%= f.label :power %>
  <%= f.text_field :power %><br>
  <%= f.label :power_level %>
  <%= f.number_field :power_level %><br>

app/views/superheros/_full_form.html.erb
<%= form_for superhero do |f| %>
  <%= render partial:'form', locals: {superhero: superhero, f: f} %>
  <%= f.collection_select :team_id, Team.all, :id, :name %>
<%= f.submit %>
<% end %>

app/views/superheros/_superhero.html.erb
<h1><%= superhero.name %></h1>
<h2>A.K.A. <%= superhero.alias %></h2>
<p>Power: <%= superhero.power %></p>
<p>Power Level: <%= "💪" * superhero.power_level %></p>
<p>Good: True</p>

app/views/superheros/edit.html.erb
<h1>Update the Superhero</h1>
<%= render partial:'full_form', locals: {superhero: @superhero} %>

app/views/superheros/index.html.erb
<h1>All Superheroes</h1>
<ul><% @superheros.each do |superhero| %>
  <li><%= link_to superhero.alias, superhero %></li>
<% end %>
</ul>

app/views/superheros/new.html.erb
<h1>Forge Your Hero!</h1>
<%= render partial:'full_form', locals: {superhero: @superhero} %>

app/views/superheros/show.html.erb
<%= render partial:'superhero', locals: {superhero: @superhero} %>
<% if @superhero.team %>
<p>Team: <%= @superhero.team.name %></p>
<% end %>

<%= button_to "Edit #{@superhero.name}", edit_superhero_path, method: :get %>
<%= button_to "Delete #{@superhero.name}", superhero_path, method: :delete %>